[package]
name = "amm-proxy-contract"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name="amm_proxy_contract"

[dependencies]
solana-program = "2.3.0"
arrayref = "0.3.7"
borsh = "1.5.7"